baseURL = "https://example.com"
title = "Laís Chaves"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Personal blog."
  copyright = "Copyright © 2021 Laís Chaves"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "sobre"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
